### ISSUE TITLE
Check that we implement the fix for Create Account

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/woocommerce#41] opened 2015-03-02 12:26 UTC
Fixed in #35 For 1.23.3 Implement the same logics.

**Comment by Boxedsolutions** [comment] 2015-03-25 17:52
Could you check so that is possible to create a account when checkout?

**Comment by joakim-combain** [comment] 2015-03-26 07:17
There seems to be an issue with Bank and Card. I get the following error message when trying to create an account while checking out with bank and card.

Billmate Error Code:9003. The function name is required. Make sure that you provide valid Content-Type and Content-Length in the header.

**Comment by Boxedsolutions** [comment] 2015-03-27 18:21
Cant reproduce. It could have been any session or some cache or something.

**Comment by joakim-combain** [comment] 2015-03-30 05:53
I'm still getting it.

Here are steps to reproduce.

1. Make sure you are logged out as admin and everything.
2. Add both articles to cart.
3. Go to checkout and fill all your information.
4. Choose to create an account and give a password.
5. Now choose bank or card and press send order.
 
This should generate this error message. Also, I'm doing this in incognito.

**Comment by Boxedsolutions** [comment] 2015-04-09 08:53
Found the problem, It wasnt correctly utf8_encoded

**Comment by joakim-combain** [comment] 2015-04-13 11:21
This issue is fixed. Closing it.

**Closed by joakim-combain** 2015-04-13 11:21 UTC
Labels: Developed, enhancement
