### ISSUE TITLE
Ordermails not beeing sent

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#152] opened 2015-12-29 08:03 UTC
Client reported this.

**Comment by andyjohansson** [comment] 2015-12-29 08:04
Victor Auren will complement with more info.

**Comment by Boxedsolutions** [comment] 2015-12-30 13:54
Is the cause of #153

**Comment by Boxedsolutions** [comment] 2015-12-30 14:30
Verify mails sent

**Comment by Aviree** [comment] 2016-01-05 13:44
Tested purchases with all four methods and all send an ordermail. I had to activate bankpayment manuell because it got wrong status. It has "Mottagen (Obetald)" even I set the status in settings to Standard. 

I checked Billmate Online and the status was paid.

**Comment by andyjohansson** [comment] 2016-01-08 15:28
Will test this when I get teststore.

**Comment by Boxedsolutions** [comment] 2016-01-18 07:25
Is ordermail going out @Aviree

**Comment by Aviree** [comment] 2016-01-18 11:04
It works with card, invoice and partpayment. But not with bankpayment. It says that it's waiting for payment in the orderstatus in Woocommerce. In API and Billmate online it says Paid.

**Comment by andyjohansson** [comment] 2016-01-25 04:28
Anything new @Boxedsolutions & @Aviree?

**Comment by Aviree** [comment] 2016-01-25 10:05
Tested all paymentmethods and it worked as it should. 
Closing Issue

**Closed by Aviree** 2016-01-25 10:05 UTC
Labels: bug
